Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -48,15 +48,6 @@ jobs:
       run: mvn -B clean package --file "${{ matrix.api }}/pom.xml"
 
             # Check if JAR file was created
-    - name: Verify JAR file exists
-      run: |
-          if [ ! -f "${{ matrix.api }}/target/${{ matrix.api }}-0.0.1-SNAPSHOT.jar" ]; then
-            echo "JAR file not found!"
-            exit 1
-          else
-            echo "JAR file exists."
-          fi
-
   docker:
     needs: build
     runs-on: ubuntu-latest
@@ -66,6 +57,15 @@ jobs:
           - User  
         
     steps:
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f "${{ matrix.api }}/target/${{ matrix.api }}-0.0.1-SNAPSHOT.jar" ]; then
+            echo "JAR file not found!"
+            exit 1
+          else
+            echo "JAR file exists."
+          fi
+    
       - name: Check out the code
         uses: actions/checkout@v4
 
